// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhliggyxaejmjieypbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobGlnZ3l4YWVqbWppZXlwYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDYxMTYsImV4cCI6MjA2OTgyMjExNn0.vb6UVQ4_emDdTmhrK5wYxik8vxMJUtieikMbfT8CNNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});